name: "Build and Test"
description: "Checks out the repository, builds the code and executes tests"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
  - name: Set up JDK 1.8
    uses: actions/setup-java@v1
    with:
      java-version: 1.8
  - name: Setup Android SDK
    uses: android-actions/setup-android@v2
  - name: "Gradle Build and Test"
    run: ./gradlew --no-daemon assemble build check allTests connectedAndroidTest
