name: "Android Emulator Integration Test"
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - synchronize
jobs:
  review:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12'
          cache: gradle
      - name: Run Android Device Tests
        uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 29
          script: gradle connectedAndroidTest