name: "Android Emulator Integration Test"
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - synchronize
jobs:
  review:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Update Android SDK Manager
        run: sdkmanager --update
      - name: Install Android emulator API V33 VM image
        run: echo y | sdkmanager --install "system-images;android-33;google_apis;x86_64"
      - name: Create AVD
        run: echo "no" | avdmanager create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-33;google_apis;x86_64'
      - name: Install Android latest android emulator
        run: sdkmanager --install emulator --channel=0
      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          passphrase: ${{ secrets.GPG_SIGNING_PASSWORD }}
      - name: Tests with Gradle
        run: gradle connectedAndroidTest
