name: "Build and Test"
on:
  push:
    branches: [ main ]
jobs:
  job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-and-test
      - uses: ./.github/actions/deploy