name: "Build Test and Deploy"
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          passphrase: ${{ secrets.GPG_SIGNING_PASSWORD }}
      - name: Test and deploy with Gradle
        uses: reactivecircus/android-emulator-runner@v2
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        with:
          api-level: 29
          script: ./gradlew --no-daemon assemble build check allTests connectedAndroidTest publishAllPublicationsToSonatypeRepository publishJsNpmPublicationToNpmjs publish closeAndReleaseRepository
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs