name: "Build and Test"
on:
  pull_request:
    types:
      - ready_for_review
      - review_requested
      - synchronize
      - reopened
      - opened
jobs:
  review:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          passphrase: ${{ secrets.GPG_SIGNING_PASSWORD }}
      - name: Tests with Gradle
        run: gradle assemble pack build check allTests publishToMavenLocal
